# take raw text generated by the Keynote parser and put data into the database
import sqlite3

import Chinese

with open("out.txt") as file:
    songs = []
    title = ''
    lyrics = ''
    state = 'none'
    first = True
    for line in file:
        s = line.strip()
        if s == '#Title':
            if (not first):
                songs.append([title, lyrics])
            else:
                first = False
            title = ''
            lyrics = ''
            state = 'title'
        elif s == '#Page':
            if state == 'lyrics':
                lyrics += '\n'
            state = 'lyrics'
        else:
            if state == 'title':
                title = s
            elif state == 'lyrics':
                lyrics += s + '\n'

con = sqlite3.connect("songs.sqlite3")
cur = con.cursor()
cur.execute("CREATE TABLE IF NOT EXISTS song(id integer primary key autoincrement, title, lyrics)")

for song in songs:
    cur.execute("INSERT INTO song VALUES(NULL, ?, ?)", (Chinese.format(song[0]), Chinese.format(song[1])))

con.commit()

# songs = cur.execute("SELECT * FROM song").fetchall()
# for song in songs:
#     print('Title : ' + song[1])
#     print('Lyrics: ' + song[2])

con.close()
